In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
# Sample reviews
sentences = [
    "i loved this movie it was fantastic",
    "what an amazing and wonderful experience",
    "best film i have seen in a long time",
    "absolutely incredible acting and great plot",
    "i hated this movie it was terrible",
    "worst film ever completely waste of time",
    "awful acting and horrible script",
    "boring and completely disappointing experience"
]

In [3]:
labels = np.array([1,1,1,1,0,0,0,0], dtype=np.float32)

In [4]:
max_len = 10
vectorizer = tf.keras.layers.TextVectorization(output_mode = 'int', output_sequence_length = max_len)

In [5]:
vectorizer.adapt(sentences)

In [6]:
vocab_size = len(vectorizer.get_vocabulary())

In [7]:
vocab_size

40

In [8]:
x_train = vectorizer(np.array(sentences)).numpy()
y_train = labels

In [9]:
print("Shape of X_train:", x_train.shape)
print("Vocabulary Size:", vocab_size)

Shape of X_train: (8, 10)
Vocabulary Size: 40


In [20]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(max_len,)),
    tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=8, mask_zero=True),
    tf.keras.layers.LSTM(units=16, return_sequences=False),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, 10, 8)               │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 16)                  │           1,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,937 (7.57 KB)

 Trainable params: 1,937 (7.57 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [25]:
model.fit(
    x_train,
    y_train,
    epochs=150,
    verbose=2
)

Epoch 1/150
1/1 - 0s - 101ms/step - accuracy: 1.0000 - loss: 0.0217
Epoch 2/150
1/1 - 0s - 76ms/step - accuracy: 1.0000 - loss: 0.0213
Epoch 3/150
1/1 - 0s - 112ms/step - accuracy: 1.0000 - loss: 0.0209
Epoch 4/150
1/1 - 0s - 72ms/step - accuracy: 1.0000 - loss: 0.0206
Epoch 5/150
1/1 - 0s - 64ms/step - accuracy: 1.0000 - loss: 0.0202
Epoch 6/150
1/1 - 0s - 69ms/step - accuracy: 1.0000 - loss: 0.0199
Epoch 7/150
1/1 - 0s - 76ms/step - accuracy: 1.0000 - loss: 0.0196
Epoch 8/150
1/1 - 0s - 74ms/step - accuracy: 1.0000 - loss: 0.0193
Epoch 9/150
1/1 - 0s - 58ms/step - accuracy: 1.0000 - loss: 0.0190
Epoch 10/150
1/1 - 0s - 58ms/step - accuracy: 1.0000 - loss: 0.0187
Epoch 11/150
1/1 - 0s - 71ms/step - accuracy: 1.0000 - loss: 0.0184
Epoch 12/150
1/1 - 0s - 95ms/step - accuracy: 1.0000 - loss: 0.0182
Epoch 13/150
1/1 - 0s - 82ms/step - accuracy: 1.0000 - loss: 0.0179
Epoch 14/150
1/1 - 0s - 86ms/step - accuracy: 1.0000 - loss: 0.0176
Epoch 15/150
1/1 - 0s - 80ms/step - accuracy: 1.0000 - 

In [27]:
test_reviews = np.array([
    "this movie was fantastic and wonderful",
    "terrible film complete waste"
])

test = vectorizer(np.array(test_reviews)).numpy()

pred = model.predict(test)

print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
[[0.10539316]
 [0.02452301]]


In [28]:
print("Vectorized test sentence:\n", test[0])

Vectorized test sentence:
 [ 6  7  4 30  2 14  0  0  0  0]


In [29]:
print("Vocabulary:", vectorizer.get_vocabulary())
print("Test tokens:", test)

Vocabulary: ['', '[UNK]', np.str_('and'), np.str_('i'), np.str_('was'), np.str_('time'), np.str_('this'), np.str_('movie'), np.str_('it'), np.str_('film'), np.str_('experience'), np.str_('completely'), np.str_('acting'), np.str_('worst'), np.str_('wonderful'), np.str_('what'), np.str_('waste'), np.str_('terrible'), np.str_('seen'), np.str_('script'), np.str_('plot'), np.str_('of'), np.str_('loved'), np.str_('long'), np.str_('incredible'), np.str_('in'), np.str_('horrible'), np.str_('have'), np.str_('hated'), np.str_('great'), np.str_('fantastic'), np.str_('ever'), np.str_('disappointing'), np.str_('boring'), np.str_('best'), np.str_('awful'), np.str_('an'), np.str_('amazing'), np.str_('absolutely'), np.str_('a')]
Test tokens: [[ 6  7  4 30  2 14  0  0  0  0]
 [17  9  1 16  0  0  0  0  0  0]]
