In [32]:
import tensorflow as tf

tensor = tf.constant([
    [1,2,3],
    [4,5,6]
])

print(tensor)


print(tensor.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)


# Tensor Indexing

In [33]:
tensor_1 = tf.constant([
    [10,20,30],
    [40,50,60]
])

print(tensor_1)

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [34]:
print(tensor_1[0,0])

tf.Tensor(10, shape=(), dtype=int32)


In [35]:
print(tensor_1[1,1])

tf.Tensor(50, shape=(), dtype=int32)


In [36]:
print(tensor_1[1])

tf.Tensor([40 50 60], shape=(3,), dtype=int32)


In [37]:
print(tensor_1[0,2])

tf.Tensor(30, shape=(), dtype=int32)


# Tensor Slicing 

In [38]:
tensor = tf.constant([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(tensor.shape)

(3, 3)


In [39]:
print(tensor)

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)


In [40]:
print(tensor[:2])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [41]:
print(tensor[1::2])

tf.Tensor([[40 50 60]], shape=(1, 3), dtype=int32)


In [42]:
print(tensor[: , :2])

tf.Tensor(
[[10 20]
 [40 50]
 [70 80]], shape=(3, 2), dtype=int32)


In [43]:
print(tensor[1::1])

tf.Tensor(
[[40 50 60]
 [70 80 90]], shape=(2, 3), dtype=int32)


In [44]:
print(tensor[: , 2])

tf.Tensor([30 60 90], shape=(3,), dtype=int32)


# Tensor Reshaping

In [45]:
tensor = tf.constant([1,2,3,4,5,6])

reshaped = tf.reshape(tensor,(2,3))

print(reshaped)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [46]:
reshaped  =tf.reshape(tensor,(3,2))
print(reshaped)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# Expanding Dimensions 

In [47]:
tensor = tf.constant([1,2,3])
print (tensor.shape)
expanded = tf.expand_dims(tensor,axis=0)

print(expanded)

print(expanded.shape)

(3,)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
(1, 3)


In [48]:
expanded = tf.expand_dims(tensor,axis=1)

print(expanded)


tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


# Squeeze

In [49]:
tensor = tf.constant([[1,2,3]])

print(tensor.shape)

(1, 3)


In [50]:
squeezed = tf.squeeze(tensor)

print(squeezed)
print(squeezed.shape)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
(3,)


# Changing DataType

In [51]:
tensor = tf.constant([1,2,3])

print(tensor.dtype)

<dtype: 'int32'>


In [52]:
new_tensor = tf.cast(tensor , tf.float32)

print(new_tensor.dtype)

<dtype: 'float32'>


# Creating Random Tensor

In [53]:
random = tf.random.uniform(
    shape=(2,3),
    minval=0,
    maxval=10,
    dtype=tf.int32
)

print(random)

tf.Tensor(
[[4 6 0]
 [8 9 1]], shape=(2, 3), dtype=int32)


In [54]:
# Tensor With Decimal Values 

random = tf.random.normal(shape=(2,3))

print(random)

tf.Tensor(
[[-0.2308161 -1.4361515 -1.1754446]
 [-1.5621369 -1.0593985  1.3828458]], shape=(2, 3), dtype=float32)


# Tensor to Numpy

In [55]:
tensor = tf.constant([1,2,3])

array = tensor.numpy()

print(array)

print(array.dtype)

[1 2 3]
int32


In [56]:
import numpy as np

In [57]:
array = np.array([1,2,3])

tensor = tf.constant(array)

print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


# Useful Tensor Operations

In [58]:
tensor = tf.constant([10,20,30])
print(tensor)

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [59]:
print(tf.reduce_max(tensor))

tf.Tensor(30, shape=(), dtype=int32)


In [60]:
print(tf.reduce_min(tensor))

tf.Tensor(10, shape=(), dtype=int32)


In [61]:
print(tf.reduce_mean(tensor))

tf.Tensor(20, shape=(), dtype=int32)


In [62]:
print(tf.reduce_sum(tensor))

tf.Tensor(60, shape=(), dtype=int32)


# Mini Exercise

In [66]:
tesnsor = tf.constant([1,2,3,4,5,6])
print(tensor)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [68]:
reshaped = tf.reshape(tensor,(2,3))
print(reshaped)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [69]:
reshaped = tf.reshape(tensor,(3,2))
print(reshaped)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [73]:
tensor = tf.constant([[1,2,3]])

print(tensor)

squeezed = tf.squeeze(tensor)

print(squeezed)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [76]:
tensor = tf.constant([10,20,30])

expanded  = tf.expand_dims(tensor, axis=0)

print(expanded)

tf.Tensor([[10 20 30]], shape=(1, 3), dtype=int32)


In [77]:
expanded = tf.expand_dims(tensor, axis=1)

print(expanded)

tf.Tensor(
[[10]
 [20]
 [30]], shape=(3, 1), dtype=int32)
