In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf

print(tf.__version__)

2.21.0


In [3]:
tensors =tf.constant([1,2,3,4,5])
print(tensors)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [4]:
#1D
scalar  = tf.constant(10)
print(scalar)

tf.Tensor(10, shape=(), dtype=int32)


In [5]:
#2D
vector = tf.constant([1,2,3,4])
print(vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [6]:
#3D
matrix = tf.constant([
    [1,2],
    [3,4]
])

print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [7]:
tensor_3d = tf.constant([[
    [1,2],
    [3,4]],

    [[5,6],
     [7,8]]
                        ])
print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [8]:
tensor = tf.constant([[1,2],[3,4]])

print(tensor.shape)

(2, 2)


In [9]:
print(tensor.dtype)

<dtype: 'int32'>


In [10]:
print(tensor.ndim)

2


In [11]:
a = tf.constant([1,2,3])

b = tf.constant([4,5,6])



In [12]:
print(a+b)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [13]:
print(a*b)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [14]:
c = tf.constant([[1,2],
                 [3,4]])
d = tf.constant([[5,6],
                 [7,8]])

print(tf.matmul(c,d))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# Practice

In [24]:
scalar = tf.constant(10)

print(scalar)


tf.Tensor(10, shape=(), dtype=int32)


In [27]:
print(scalar.shape)
print(scalar.dtype)
print(type(scalar))
print(scalar.ndim)

()
<dtype: 'int32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
0


In [17]:
vector = tf.constant([1,2,3,4])

print(vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [28]:
print(vector.shape)
print(vector.dtype)
print(type(vector))
print(vector.ndim)

(4,)
<dtype: 'int32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
1


In [20]:
matrix = tf.constant([
    [1,2],
    [3,4]])

print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [30]:
print(matrix.shape)
print(matrix.dtype)
print(type(matrix))
print(matrix.ndim)

(2, 2)
<dtype: 'int32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
2


In [32]:
a  = tf.constant([1,2,3,4,5])

b = tf.constant([6,7,8,9,0])

print(a+b)
print(a*b)

tf.Tensor([ 7  9 11 13  5], shape=(5,), dtype=int32)
tf.Tensor([ 6 14 24 36  0], shape=(5,), dtype=int32)


In [34]:
c = tf.constant([
    [1,2],
    [3,4]])
d = tf.constant([
    [5,6],
    [7,8]])

print(c+d)
print(c*d)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [42]:
tensor_3d = tf.constant([
    [[1,2],
    [3,4]],

    [[5,6],
    [7,8]]])

print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [43]:
print(tensor_3d.shape)
print(type(tensor_3d))
print(tensor_3d.dtype)
print(tensor_3d.ndim)

(2, 2, 2)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<dtype: 'int32'>
3
